version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/Order-service"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "github-actions"
    directory: "/Order-service"
    schedule:
      interval: "weekly"
    labels:
      - "ci-cd"
      - "dependencies"