apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: b8t
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: gopnikradotinsky/order-service-order-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key:  EUREKA_URL
            - name: SERVER_PORT
              value: "8083"
            - name: MYSQL_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: DATABASE_URL
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: password
