apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: b8t
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort
