spring:
  application:
    name: order-service  # The name for the API Gateway service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery for routing
          lower-case-service-id: true  # Optional, makes the service ID lowercase




